name: Build Theos Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang curl git perl llvm xz-utils zip unzip
        mkdir -p $HOME/theos/sdks
        
        # Download WORKING iOS SDK from reliable source
        curl -sL -o sdk.tar.xz https://github.com/lechium/sdks/raw/main/iPhoneOS16.2.sdk.tar.xz
        
        # Extract SDK
        tar -xJf sdk.tar.xz -C $HOME/theos/sdks/
        rm sdk.tar.xz
        
        # Verify SDK extraction
        ls -la $HOME/theos/sdks/
        
    - name: Build project
      run: |
        cd $GITHUB_WORKSPACE
        make clean
        make package FINALPACKAGE=1
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-package
        path: packages/
