name: Build Theos Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Theos with pre-built SDK
      uses: 1Conan/theos-action@v1
      with:
        ios_sdk: 16.2
        
    - name: Build project
      run: |
        make clean
        make package FINALPACKAGE=1
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-package
        path: packages/
