name: Build Theos Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV
        
        # Use whatever SDK comes with Theos (often works)
        ls -la $HOME/theos/sdks/ || true
        
    - name: Build project
      run: |
        cd $GITHUB_WORKSPACE
        make clean
        make package FINALPACKAGE=1
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-package
        path: packages/
