name: Build Theos Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang curl git perl llvm xz-utils file
        mkdir -p $HOME/theos/sdks
        
        # Download SDK and try multiple extraction methods
        curl -sL -o sdk_file https://github.com/theos/sdks/raw/master/iPhoneOS16.2.sdk.tar.xz
        
        # Try different extraction methods
        if file sdk_file | grep -q "XZ compressed"; then
          echo "Extracting as XZ format..."
          tar -xJf sdk_file -C $HOME/theos/sdks
        elif file sdk_file | grep -q "bzip2"; then
          echo "Extracting as bzip2 format..."
          tar -xjf sdk_file -C $HOME/theos/sdks
        elif file sdk_file | grep -q "gzip"; then
          echo "Extracting as gzip format..."
          tar -xzf sdk_file -C $HOME/theos/sdks
        else
          echo "Unknown file format, trying automatic extraction..."
          tar -xf sdk_file -C $HOME/theos/sdks
        fi
        
        # Verify extraction worked
        ls -la $HOME/theos/sdks/
        rm sdk_file
        
    - name: Build project
      run: |
        cd $GITHUB_WORKSPACE
        make clean
        make package FINALPACKAGE=1
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-package
        path: packages/
