name: Build Theos Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build using Theos Docker
      run: |
        # Use pre-built Docker image with everything installed
        docker run --rm -v $(pwd):/project ghcr.io/theos/theos:latest /bin/bash -c "
          cd /project
          make clean
          make package FINALPACKAGE=1
        "
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-package
        path: packages/
